# Generated by Django 5.1.4 on 2025-01-30 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Quest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Название")),
                (
                    "description",
                    models.CharField(max_length=300, verbose_name="Описание"),
                ),
                (
                    "task_time",
                    models.DurationField(verbose_name="Время выполнения квеста"),
                ),
                (
                    "bonus_power_points",
                    models.IntegerField(default=0, verbose_name="Очки за квест"),
                ),
                (
                    "bonus_power",
                    models.CharField(
                        choices=[
                            ("S", "strenght"),
                            ("I", "intelegence"),
                            ("A", "agility"),
                            ("W", "Wisdom"),
                        ],
                        max_length=50,
                        verbose_name="Повышенная характеристика",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserQuest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_quest_time",
                    models.DateTimeField(verbose_name="Время начала квеста"),
                ),
                (
                    "end_quest_time",
                    models.DateTimeField(verbose_name="Время окончания квеста"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("A", "active"),
                            ("C", "completed"),
                            ("F", "failed"),
                            ("N", "not started"),
                        ],
                        max_length=50,
                        verbose_name="Статус квеста",
                    ),
                ),
                (
                    "quest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quest.quest",
                        verbose_name="Квест",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="quest",
            name="user",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="user_quest",
                through="quest.UserQuest",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
