# Generated by Django 5.1.4 on 2025-01-30 18:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quest", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="quest",
            name="user",
            field=models.ManyToManyField(
                related_name="user_quest",
                through="quest.UserQuest",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
