# Generated by Django 5.1.5 on 2025-01-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0002_alter_quest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquest',
            name='end_quest_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время окончания квеста'),
        ),
        migrations.AlterField(
            model_name='userquest',
            name='start_quest_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время начала квеста'),
        ),
    ]
