# Generated by Django 5.1.5 on 2025-01-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0003_alter_userquest_end_quest_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquest',
            name='status',
            field=models.CharField(choices=[('A', 'active'), ('C', 'completed'), ('F', 'failed'), ('N', 'not started')], default='N', max_length=50, verbose_name='Статус квеста'),
        ),
    ]
