# Generated by Django 5.1.4 on 2025-01-13 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strenght", models.IntegerField(default=5)),
                ("intelegence", models.IntegerField(default=5)),
                ("agility", models.IntegerField(default=5)),
                ("wisdom", models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "description",
                    models.CharField(max_length=100, verbose_name="Описание"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("H", "Hands"),
                            ("C", "Chest"),
                            ("L", "Legs"),
                            ("W", "Weapon"),
                        ],
                        max_length=50,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "bonus_strenght",
                    models.IntegerField(default=0, verbose_name="Дополниткльная сила"),
                ),
                (
                    "bonus_intelegence",
                    models.IntegerField(
                        default=0, verbose_name="Дополнительный интеллект"
                    ),
                ),
                (
                    "bonus_agility",
                    models.IntegerField(
                        default=0, verbose_name="Доплнительная ловкость"
                    ),
                ),
                (
                    "bonus_wisdom",
                    models.IntegerField(
                        default=0, verbose_name="Дополнительная мудрость"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CharacterEuipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="char_equipment",
                        to="character.character",
                    ),
                ),
                (
                    "chest",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="char_eq_chest",
                        to="character.equipment",
                    ),
                ),
                (
                    "hands",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="char_eq_hands",
                        to="character.equipment",
                    ),
                ),
                (
                    "legs",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="char_eq_legs",
                        to="character.equipment",
                    ),
                ),
                (
                    "weapon",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="char_eq_weap",
                        to="character.equipment",
                    ),
                ),
            ],
        ),
    ]
