# Generated by Django 5.1.4 on 2025-01-13 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CharacterEuipment",
            new_name="CharacterEquipment",
        ),
        migrations.AddField(
            model_name="character",
            name="user",
            field=models.OneToOneField(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
