# Generated by Django 5.1.5 on 2025-01-15 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_rename_charactereuipment_characterequipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterequipment',
            name='character',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='char_equipment', to='character.character'),
        ),
        migrations.AlterField(
            model_name='characterequipment',
            name='chest',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='char_eq_chest', to='character.equipment'),
        ),
        migrations.AlterField(
            model_name='characterequipment',
            name='hands',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='char_eq_hands', to='character.equipment'),
        ),
        migrations.AlterField(
            model_name='characterequipment',
            name='legs',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='char_eq_legs', to='character.equipment'),
        ),
        migrations.AlterField(
            model_name='characterequipment',
            name='weapon',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='char_eq_weap', to='character.equipment'),
        ),
    ]
