# Generated by Django 5.1.4 on 2025-01-18 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0004_alter_characterequipment_character_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characterequipment",
            name="chest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="char_eq_chest",
                to="character.equipment",
            ),
        ),
        migrations.AlterField(
            model_name="characterequipment",
            name="hands",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="char_eq_hands",
                to="character.equipment",
            ),
        ),
        migrations.AlterField(
            model_name="characterequipment",
            name="legs",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="char_eq_legs",
                to="character.equipment",
            ),
        ),
        migrations.AlterField(
            model_name="characterequipment",
            name="weapon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="char_eq_weap",
                to="character.equipment",
            ),
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("money", models.IntegerField(default=0)),
                (
                    "character",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="char_invetory",
                        to="character.character",
                    ),
                ),
                (
                    "equipment",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="char_inv",
                        to="character.equipment",
                    ),
                ),
            ],
        ),
    ]
