# Generated by Django 5.1.4 on 2025-01-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0005_alter_characterequipment_chest_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="equipment",
            field=models.ManyToManyField(
                related_name="char_inv", to="character.equipment"
            ),
        ),
    ]
